### ISSUE TITLE
Error while running Gradle task: invalid ELF header.

### ISSUE THREAD

**Issue by kyzsuukii** [bdloser404/Fluttermux#2]
![Screenshot_20230911-174533_Termux.png](https://github.com/bdloser404/Fluttermux/assets/110718021/d6df2c1b-7562-475b-8b9f-ecbfd12ce556)

i try run `flutter build apk [--debug]`
but got this issue

**Comment by kyzsuukii** [comment]
> `fluttermux --patch java` 
> 
> try this 

still same

**Comment by bdloser404** [comment]
> still same
tthis error is bcz of mismatch arch. make sure your device is aarch64

**Comment by bdloser404** [comment]
if you get this error even you are using arm64 then, 
you need to delete jdk19.0.2 first. 

cd `~/.fluttermux ;ls ` delete jdk-19.0.2 folder & tar.xz . 

then try,  `fluttermux --install` 
i

**Comment by bdloser404** [comment]
> still same

if above solution doesn't work for you then please share more details:

`ldd ~/.fluttermux/jdk-19.0.2/bin/java`

**Comment by susandahal** [comment]
Can you once run pacman -S gpkg-dev once,install all packages and then try this again?

**Comment by bdloser404** [comment]
> Can you once run pacman -S gpkg-dev once,install all packages and then try this again?

if this was glibc problem then flutter should not work

**Comment by kyzsuukii** [comment]
![Screenshot_20230911-232355_Termux.png](https://github.com/bdloser404/Fluttermux/assets/110718021/a3a55a8b-f2a2-4970-9957-e0601ce5f088)

still not fixing

**Comment by kyzsuukii** [comment]
> > still not fixing
> 
> now its confrim that problem is coming from java 
> - you can use `openjdk-internal-17` version from pkg manager
> 
> > [!NOTE]
> > if you use java from pkg manager then you need to change path of `JAVA_HOME` <br>
> additionally, you need to modify  `yourapp/android/gradle/wrapper/gradle-wrapper.properties` DistributionUrl to gradle 7.5
> 
> if  you need fix for jdk19 then i need more details
> `ldd ~/.fluttermux/jdk-19.0.2/bin/java`


![Screenshot_20230911-233848_Termux.png](https://github.com/bdloser404/Fluttermux/assets/110718021/0adc7bbf-3697-4a2c-a325-57ba46de3dd4)

**Comment by bdloser404** [comment]
thanks now here is the problem

ld-android-so is triaging .

`export LD_LIBRARY_PATH=""`

should fix it

**Comment by kyzsuukii** [comment]
> thanks now here is the problem
> 
> ld-android-so is triaging . This may bcz you already have java installed or your some of packages using LD_LIBRARY_PATH for system/ib64/.. problem is not clear why both interpreter ld-android.so & ld-linux-aarch64 is calling.
> 
> 
> try this:
> 
>  **NO MATTER IF ERROR NOT FIX**
>  
>  `pacman -S openjdk-17 --overwrite="*"`
>  
>  ###  ADD Enviroment Variable
>  
> >add this  java home path to ~/.bashrc
> >and make sure you remove prevoius JAVA_HOME path
> 
> ` JAVA_HOME=$PREFIX/opt/openjdk`
>  `PATH=$PATH/JAVA_HOME/bin`
>  
> **you are almost done**
> now create new flutter project:
> 
> `flutter create testapp`
> `chmod +x testapp/android/gradlew`
> 
> >[!IMPORTANT]
> >**DONT RUN `fluttermux --fix gradle` ever** <br>this is only for jdk19 user
>  
>  `cd testapp`
>  `flutter build apk --debug -Pandroid.aapt2FromMavenOverride=$(which aapt2)`
>  
> 

![Screenshot_20230912-081823_Termux.png](https://github.com/bdloser404/Fluttermux/assets/110718021/129449bd-1449-4603-815d-8f3d27ec924a)

thanks my issue not solved

**Comment by kyzsuukii** [comment]
![Screenshot_20230912-090252_Termux.png](https://github.com/bdloser404/Fluttermux/assets/110718021/f46b8078-29c8-4f30-a75f-ea2b6cba8386)

but if use build release i got this new issue

**Comment by bdloser404** [comment]
> thanks my issue not solved

**YOU MEAN NOT SOLVED?**
I Can see is working as expected .

although here is some tip for you:

- after creating every new project `your_project_dir/android/gradlew` permission need to fix with `chmod` 
- for running hotreload you can pass `-Pandroid.aapt2FromMavenOverride=$(which aapt2)`
-  of add `android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2` to `android/gradle.properties` <br> then you dont need to pass it every time.

**Comment by kyzsuukii** [comment]
> 
> > thanks my issue not solved
> 
> **YOU MEAN NOT SOLVED?**
> I Can see is working as expected .
> 
> although here is some tip for you:
> 
> - after creating every new project `your_project_dir/android/gradlew` permission need to fix with `chmod` 
> - for running hotreload you can pass `-Pandroid.aapt2FromMavenOverride=$(which aapt2)`
> -  of add `android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2` to `android/gradle.properties` <br> then you dont need to pass it every time.
> 

sorry for typo 

its already fixed

but for now when build release still have issue

**Comment by bdloser404** [comment]
> but for now when build release still have issue

built release not support . but you can build release using linux_arm64/gen_snapshot
, i will discuss it later . but for now , you can close this issue.

**Comment by kyzsuukii** [comment]
> > but for now when build release still have issue
> 
> built release not support . but you can build release using linux_arm64/gen_snapshot.i will discuss it later . but for now , you can close this issue. 
> 
> 

thanks
